// Code generated by protoc-gen-go. DO NOT EDIT.
// source: example/proto/helloworld.proto

package helloworld

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type HelloRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_40e5561eeb38f461, []int{0}
}

func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (m *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(m, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type HelloReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloReply) Reset()         { *m = HelloReply{} }
func (m *HelloReply) String() string { return proto.CompactTextString(m) }
func (*HelloReply) ProtoMessage()    {}
func (*HelloReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_40e5561eeb38f461, []int{1}
}

func (m *HelloReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloReply.Unmarshal(m, b)
}
func (m *HelloReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloReply.Marshal(b, m, deterministic)
}
func (m *HelloReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloReply.Merge(m, src)
}
func (m *HelloReply) XXX_Size() int {
	return xxx_messageInfo_HelloReply.Size(m)
}
func (m *HelloReply) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloReply.DiscardUnknown(m)
}

var xxx_messageInfo_HelloReply proto.InternalMessageInfo

func (m *HelloReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type BulkInsertSingersRequest struct {
	Singers              []*Singer `protobuf:"bytes,1,rep,name=singers,proto3" json:"singers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *BulkInsertSingersRequest) Reset()         { *m = BulkInsertSingersRequest{} }
func (m *BulkInsertSingersRequest) String() string { return proto.CompactTextString(m) }
func (*BulkInsertSingersRequest) ProtoMessage()    {}
func (*BulkInsertSingersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_40e5561eeb38f461, []int{2}
}

func (m *BulkInsertSingersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BulkInsertSingersRequest.Unmarshal(m, b)
}
func (m *BulkInsertSingersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BulkInsertSingersRequest.Marshal(b, m, deterministic)
}
func (m *BulkInsertSingersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BulkInsertSingersRequest.Merge(m, src)
}
func (m *BulkInsertSingersRequest) XXX_Size() int {
	return xxx_messageInfo_BulkInsertSingersRequest.Size(m)
}
func (m *BulkInsertSingersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BulkInsertSingersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BulkInsertSingersRequest proto.InternalMessageInfo

func (m *BulkInsertSingersRequest) GetSingers() []*Singer {
	if m != nil {
		return m.Singers
	}
	return nil
}

type BulkInsertSingersReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BulkInsertSingersReply) Reset()         { *m = BulkInsertSingersReply{} }
func (m *BulkInsertSingersReply) String() string { return proto.CompactTextString(m) }
func (*BulkInsertSingersReply) ProtoMessage()    {}
func (*BulkInsertSingersReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_40e5561eeb38f461, []int{3}
}

func (m *BulkInsertSingersReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BulkInsertSingersReply.Unmarshal(m, b)
}
func (m *BulkInsertSingersReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BulkInsertSingersReply.Marshal(b, m, deterministic)
}
func (m *BulkInsertSingersReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BulkInsertSingersReply.Merge(m, src)
}
func (m *BulkInsertSingersReply) XXX_Size() int {
	return xxx_messageInfo_BulkInsertSingersReply.Size(m)
}
func (m *BulkInsertSingersReply) XXX_DiscardUnknown() {
	xxx_messageInfo_BulkInsertSingersReply.DiscardUnknown(m)
}

var xxx_messageInfo_BulkInsertSingersReply proto.InternalMessageInfo

type Singer struct {
	SingerId             int64    `protobuf:"varint,1,opt,name=singer_id,json=singerId,proto3" json:"singer_id,omitempty"`
	FirstName            string   `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	SingerInfo           []byte   `protobuf:"bytes,4,opt,name=singer_info,json=singerInfo,proto3" json:"singer_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Singer) Reset()         { *m = Singer{} }
func (m *Singer) String() string { return proto.CompactTextString(m) }
func (*Singer) ProtoMessage()    {}
func (*Singer) Descriptor() ([]byte, []int) {
	return fileDescriptor_40e5561eeb38f461, []int{4}
}

func (m *Singer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Singer.Unmarshal(m, b)
}
func (m *Singer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Singer.Marshal(b, m, deterministic)
}
func (m *Singer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Singer.Merge(m, src)
}
func (m *Singer) XXX_Size() int {
	return xxx_messageInfo_Singer.Size(m)
}
func (m *Singer) XXX_DiscardUnknown() {
	xxx_messageInfo_Singer.DiscardUnknown(m)
}

var xxx_messageInfo_Singer proto.InternalMessageInfo

func (m *Singer) GetSingerId() int64 {
	if m != nil {
		return m.SingerId
	}
	return 0
}

func (m *Singer) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Singer) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *Singer) GetSingerInfo() []byte {
	if m != nil {
		return m.SingerInfo
	}
	return nil
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "helloworld.HelloRequest")
	proto.RegisterType((*HelloReply)(nil), "helloworld.HelloReply")
	proto.RegisterType((*BulkInsertSingersRequest)(nil), "helloworld.BulkInsertSingersRequest")
	proto.RegisterType((*BulkInsertSingersReply)(nil), "helloworld.BulkInsertSingersReply")
	proto.RegisterType((*Singer)(nil), "helloworld.Singer")
}

func init() { proto.RegisterFile("example/proto/helloworld.proto", fileDescriptor_40e5561eeb38f461) }

var fileDescriptor_40e5561eeb38f461 = []byte{
	// 295 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0x41, 0x4f, 0x83, 0x40,
	0x10, 0x85, 0x5d, 0x69, 0x0a, 0x4c, 0x7b, 0x71, 0x0f, 0xcd, 0xa6, 0x46, 0x25, 0x1b, 0x63, 0x38,
	0x98, 0x36, 0xa9, 0x77, 0x0f, 0x5e, 0x6c, 0x2f, 0x1e, 0xe8, 0x0f, 0x20, 0x6b, 0x18, 0x2a, 0x71,
	0x61, 0x71, 0x97, 0x46, 0xb9, 0xfa, 0x73, 0xfc, 0x95, 0x86, 0xa5, 0x1b, 0x49, 0xac, 0xf1, 0xc6,
	0xbc, 0xf7, 0xf1, 0x98, 0x37, 0xc0, 0x25, 0x7e, 0x88, 0xb2, 0x96, 0xb8, 0xac, 0xb5, 0x6a, 0xd4,
	0xf2, 0x05, 0xa5, 0x54, 0xef, 0x4a, 0xcb, 0x6c, 0x61, 0x05, 0x0a, 0x3f, 0x0a, 0xe7, 0x30, 0x5d,
	0x77, 0x53, 0x82, 0x6f, 0x7b, 0x34, 0x0d, 0xa5, 0x30, 0xaa, 0x44, 0x89, 0x8c, 0x44, 0x24, 0x0e,
	0x13, 0xfb, 0xcc, 0x6f, 0x00, 0x0e, 0x4c, 0x2d, 0x5b, 0xca, 0xc0, 0x2f, 0xd1, 0x18, 0xb1, 0x73,
	0x90, 0x1b, 0xf9, 0x1a, 0xd8, 0xc3, 0x5e, 0xbe, 0x6e, 0x2a, 0x83, 0xba, 0xd9, 0x16, 0xd5, 0x0e,
	0xb5, 0x71, 0xb9, 0xb7, 0xe0, 0x9b, 0x5e, 0x61, 0x24, 0xf2, 0xe2, 0xc9, 0x8a, 0x2e, 0x06, 0x7b,
	0xf5, 0x70, 0xe2, 0x10, 0xce, 0x60, 0x76, 0x24, 0xa9, 0x96, 0x2d, 0xff, 0x24, 0x30, 0xee, 0x05,
	0x7a, 0x0e, 0x61, 0xcf, 0xa7, 0x45, 0x66, 0x57, 0xf1, 0x92, 0xa0, 0x17, 0x36, 0x19, 0xbd, 0x00,
	0xc8, 0x0b, 0x6d, 0x9a, 0xd4, 0xb6, 0x39, 0xb5, 0x8b, 0x86, 0x56, 0x79, 0x12, 0x25, 0x76, 0xef,
	0x4a, 0xe1, 0x5c, 0xcf, 0xba, 0x41, 0x27, 0x58, 0xf3, 0x0a, 0x26, 0x2e, 0xb8, 0xca, 0x15, 0x1b,
	0x45, 0x24, 0x9e, 0x26, 0x70, 0x88, 0xae, 0x72, 0xb5, 0xfa, 0x22, 0xe0, 0x3f, 0x6a, 0xc4, 0x06,
	0x35, 0xbd, 0x87, 0x60, 0x2b, 0x5a, 0x7b, 0x1f, 0xca, 0x86, 0x9d, 0x86, 0x67, 0x9d, 0xcf, 0x8e,
	0x38, 0x5d, 0x9d, 0x13, 0x9a, 0xc2, 0xd9, 0xaf, 0xaa, 0xf4, 0x7a, 0x88, 0xff, 0x75, 0xd3, 0x39,
	0xff, 0x87, 0xb2, 0x1f, 0x78, 0x1e, 0xdb, 0x9f, 0x7e, 0xf7, 0x1d, 0x00, 0x00, 0xff, 0xff, 0xac,
	0x0d, 0x66, 0x24, 0x16, 0x02, 0x00, 0x00,
}
